### ISSUE TITLE
Cone of silence

### ISSUE THREAD

**Issue by aidanlister** [pboehm/django-data-migration#1]
Hey, great module! Finally an ETL framework for Django.

It'd be great to add some language around the run process itself, often it dies with no feedback. E.g. an ImportError in the data_migration_spec.py file will fail silently. Right now I'm running a migration that stops a quarter way through and I have no idea :/

Maybe something like:

```
def handle(self, *args, **options):
    translation.activate(settings.LANGUAGE_CODE)

    excluded_apps = options.get('excluded_apps', [])

    self.stdout.write('Importing migrations ...')
    Importer.import_all(excludes=excluded_apps)

    self.stdout.write('Running migrations ...')
    Migrator.migrate(
        commit=options.get('commit_changes', False),
        log_queries=options.get('logquery', False)
    )
    self.stdout.write('Finished.')
```

PS. It'd be great if we could change the name of the migrate command, it's awkward explaining it to the client ...

**Comment by pboehm** [comment]
You can get more feedback, in case of an error, when you add the `--traceback` option to the command which will print the Stacktrace when an exception occurs.

The command name has been selected in a bad mood (looking at a crappy schema) ... What would you suggest? `migrate` is already taken by South. What about `migrate_legacy_data`?

**Comment by pboehm** [comment]
I've changed the management command to `migrate_legacy_data` which should be more appropriate. `migrate_this_shit` is also supported, as it calls `migrate_legacy_data` internally.

I've added slithly more status messages. I hope that this satisfies your requirements.

You should install the latest version via `pip`.

**Comment by aidanlister** [comment]
Excellent work sir!

Don't worry, profanity runs deep through my code too :)

I'm thinking that "migrate_legacy_data" is not a good name. The "migrate" concept in Django is heavily tied to migrating between versions of Django, and in Django 1.7 "migrate" becomes a core command, so it's going to be hard to google your app.

Maybe we call it something to do with Extract, Transform, Load or ETL which is the CS concept your app is implementing.

I'm not sure it's worth the effort to rename it, but maybe you'd call it: django-etl ... and the command would be "runetl"

**Comment by aidanlister** [comment]
PS. Have you got plans to keep building this out? Have you used any other ETL frameworks before? I'm doing a big ETL job at the moment so I'd enjoy giving you some feedback and helping add some features if you'd be keen.

**Comment by pboehm** [comment]
I have heard the first time about ETL but it describes a common a common problem to me. 

This app has been written initially for an internal support system, which has been rewritten in Django. So this app implements more a one-time "migration", because of that, the app name works for me. My main intention with open-sourcing it was, to help people in the same situation (transition from a crappy PHP project to a well structured django project).

When you take this app as your basis and make the required changes to be ETL compliant, I will integrate it. So please fork it ...
