### ISSUE TITLE
Provide a way of exception handling a failed insert

### ISSUE THREAD

**Issue by aidanlister** [pboehm/django-data-migration#3]
Is it possible to provide a exception handler, the default which would be to re-raise?

For example I get:

```
django.db.utils.IntegrityError: null value in column "sequence_month" violates not-null constraint
DETAIL:  Failing row contains (17994, 2014-02-25 04:34:50.752919+00, 2014-02-25 04:34:50.752969+00, 20509, 2, t, 3, null, null, null, 2013-06-12, null).
```

This doesn't give me any identifying information because 17994 points to a row that hasn't been created yet ... and the column description has replaced the reference number I could use to look it up with the new key (17994).

Cheers :)

**Comment by pboehm** [comment]
I will develop a working solution as soon as possible (Thursday), because it is a common problem.

**Comment by pboehm** [comment]
Please upgrade to 0.1.5 where a new hook has been introduced ...

**Comment by aidanlister** [comment]
You're amazing! Thanks!

**Comment by pboehm** [comment]
http://django-data-migration.readthedocs.org/en/latest/writing_migrations.html#error-handling
