### ISSUE TITLE
Count query

### ISSUE THREAD

**Issue by aidanlister** [pboehm/django-data-migration#4]
Some databases don't return a row count, it'd be cool if you could provide a count query for each migration.

We'd then do a total = self.hasattr('rowquery') ?: rowquery or cursor.rowcount in the process_cursor function.

**Comment by pboehm** [comment]
There is now a specific hook for getting the row count. The db connection and the cursor is passed to it, so you can execute a custom count-query there.

**Comment by pboehm** [comment]
http://django-data-migration.readthedocs.org/en/latest/writing_migrations.html#data_migration.migration.Migration.hook_row_count

**Comment by aidanlister** [comment]
Thanks, you're awesome.
