### ISSUE TITLE
search_attr mismatch

### ISSUE THREAD

**Issue by richardrowe** [pboehm/django-data-migration#6]
What if we transform the data between old and new schema, where search_attr is not common between them anymore? Would be good to be able to handle this case.

**Comment by pboehm** [comment]
Could you describe a case where this happens? Did you mean the `search_attr` in the `is_a`-method or on migration level where it is used for updatable migrations.

**Comment by richardrowe** [comment]
First, I just wanted to say this is an immensely helpful library - thanks :-) 

`search_attr` in the migration, could for example be set to 'username', 'id' or 'email' at present, common, unique attribute across both the old and new schemas to allow for updates (see `allow_updates`) however if you've transformed username, email or id in the previous schema, to lets say, user_name, email_address [just an example] even though the value is the same, the attribute is different.

So the idea is to be able to...
search_attr: 'id' through 'legacy_id'

id being the attribute on the old schema, legacy_id being the attribute with same value on new schema.

Hope that made sense

**Comment by pboehm** [comment]
The normal procedure should be that your SQL query maps old column names to the new ones by using `SELECT user_name as username .....` and then the `search_attr` would be set to `username`. 

It sounds like this procedure is not used in your described case ...

**Comment by richardrowe** [comment]
Thanks! Not sure what I was thinking there...
