### ISSUE TITLE
Updating FKs based on parent new primary key

### ISSUE THREAD

**Issue by richardrowe** [pboehm/django-data-migration#7]
If I assign new primary keys to a dependency (parent) migration, how would I retrieve it in the child migration to update FK relationships assuming I still have common data between them - just not matching the old schema?

Would I need to run another query within before_transformation to get the dependent record's new PK?

Thanks

**Comment by pboehm** [comment]
I would use a global dict which translates old pk's to new pj's. In the hook_before_transformation() You will change the pk to the new one but add a new entry to the dict with the old pk as key and the new pk as value.

In your migration which has a FK-relation to the model with changed pk's, You will do a dict-lookup in hook_before_transformation() where you change the fk in `row` with the new pk using the dict-lookup.

I hope that this was not too confusing ...
