### ISSUE TITLE
example of exception handling 

### ISSUE THREAD

**Issue by richardrowe** [pboehm/django-data-migration#9]
Would it be possible to provide to put together an example of how to catch instance creation or SQL save issues and handle them appropriately. For example, if there is a duplicate record and I want to catch, and handle it appropriately how would I go about doing this?

Cheers

**Comment by pboehm** [comment]
As described here http://django-data-migration.readthedocs.org/en/latest/writing_migrations.html#error-handling, You can implement a special hook for this `hook_error_creating_instance(exception, row)`. When this method returns without an exception, the next row from the query will be processed.

The following untested code describes a possible error hadling strategy, by overriding the default error handling in your Migration class:

``` python
@classmethod
def hook_error_creating_instance(self, exception, row):
    if isinstance(exception, IntegrityError):
        # repair invalid row data. Do it in hook_before_transformation
        if row['important_field'] == None:
            row['important_field'] = "important_value"
            self.create_instance_from_row(row)

        elif "Duplicate" in unicode(exception):
            # skip duplicate entries. Might need a better test.
            return

    raise exception
```

It would be nice if you can supply some working/tested code so we can put it in the docs.

**Comment by richardrowe** [comment]
Thank you pboehm. I have no problems catching the exception string if it's a duplicate, but occasionally, and in a case I'm experiencing hook_error_creating_instance is called (Error creating instance row), but exception is empty and if I run the query through a shell it gets inserted fine [and population, and .save() of model seem fine]. 

Trying to figure out how I can debug this without any information. Debug is set to True, error log output set to '', all logging events outputted, except for certain cases where exception is empty - and if I remove the hook, execution stops there verifying it is an exception.

Hope that makes sense, and thanks again for the example!

**Comment by richardrowe** [comment]
I think I've isolated the error I was receiving to "MySQL server has gone away". Strangely, it happens on the same migration each time. I've tried increasing the max packet allocation without luck.

**Comment by richardrowe** [comment]
We may need to add;

```
try:
       .. execute query?
except (MySQLdb.OperationalError):
        self.open_db_connection
        .. execute query again?
```

**Comment by pboehm** [comment]
This "MySQL server has gone away"-error has been introduced in Django 1.6 and is a known problem. I get this timeout error in a "./manage.py shell" when it is in idle for a several minutes. https://code.djangoproject.com/ticket/21597

I wouldn't say that this is a problem which should be handled by `django-data-migration` itself, as it is limited to MySQL and should be solved by increasing the timeout on the MySQL-Server or another configuration change.

Please correct me if I'm wrong.

**Comment by richardrowe** [comment]
Thanks pboehm, I think you are right. I did manually change these values on the server without any effect, so it's not my issue. The exception I am receiving is quite odd, as there is no message with the exception.

In an attempt to debug it, I wondered if you experienced this, during first few migrations which successfully execute insert statements, when querying the MySQL database at this time I am not getting results back. As a result, I believe foreign key assignments (not using is_a()) are failing in later migration sets. 

If I catch the exceptions on a later migration sets, and let them fail but continue running until the migration script is finished, I can query the database for the successful migrations with results returned, otherwise even the successful migrations aren't saved in MySQL database.

I do apologise for these high-level questions, really odd situation where I am not getting the debug information I need to accurately identify the problem.

**Comment by pboehm** [comment]
For debugging this kind of mysterious errors I normally use `ipdb`, the Python Debugger using IPython, which you should install in every project.

Select a suitable hook method and insert `import ipdb; ipdb.set_trace()` there. You can now mess around with your instances and inspect exceptions in detail.
